version: '3.8'

services:
  mysql:
    container_name: cars_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cars_db
      MYSQL_USER: car_driver
      MYSQL_PASSWORD: drive_safety
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: